/**
 * Ptoceti Rest Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AttributeDefinitionWrapper {
  cardinality?: number;
  defaultValue?: Array<string>;
  description?: string;
  id?: string;
  name?: string;
  optionLabels?: Array<string>;
  optionValues?: Array<string>;
  type?: string;
}

