/**
 * Ptoceti Rest Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventWrapper {
  event?: EventWrapperEventEnum;
  properties?: { [key: string]: string; };
}

export enum EventWrapperEventEnum {
  NullEvent = 'NULL_EVENT',
  DeviceAddedEvent = 'DEVICE_ADDED_EVENT',
  DeviceRemovedEvent = 'DEVICE_REMOVED_EVENT',
  DriverAddedEvent = 'DRIVER_ADDED_EVENT',
  DriverRemovedEvent = 'DRIVER_REMOVED_EVENT',
  DriverAttachedEvent = 'DRIVER_ATTACHED_EVENT',
  DalAddedEvent = 'DAL_ADDED_EVENT',
  DalRemovedEvent = 'DAL_REMOVED_EVENT',
  CmDeletedEvent = 'CM_DELETED_EVENT',
  CmUpdatedEvent = 'CM_UPDATED_EVENT',
  CmLocationChangedEvent = 'CM_LOCATION_CHANGED_EVENT',
  DalDeviceModified = 'DAL_DEVICE_MODIFIED',
  DalDeviceAdded = 'DAL_DEVICE_ADDED',
  DalDeviceRemoved = 'DAL_DEVICE_REMOVED',
  DalFunctionAdded = 'DAL_FUNCTION_ADDED',
  DalFunctionRemoved = 'DAL_FUNCTION_REMOVED',
  DalFunctionPropertyChanged = 'DAL_FUNCTION_PROPERTY_CHANGED'
};



