/**
 * Ptoceti Rest Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FunctionDataWrapper {
  fields?: { [key: string]: object; };
  metadata?: { [key: string]: object; };
  timestamp?: number;
  type?: FunctionDataWrapperTypeEnum;
}

export enum FunctionDataWrapperTypeEnum {
  Level = 'FUNCTION_DATA_LEVEL',
  Keypad = 'FUNCTION_DATA_KEYPAD',
  Boolean = 'FUNCTION_DATA_BOOLEAN',
  Alarm = 'FUNCTION_DATA_ALARM'
};



