/**
 * Ptoceti Rest Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {OperationMetaDataWrapper} from './operationMetaDataWrapper';
import {PropertyMatadataWrapper} from './propertyMatadataWrapper';


export interface ItemWrapper {
  description?: string;
  deviceUid?: string;
  operationNames?: Array<string>;
  operationsMetadata?: { [key: string]: OperationMetaDataWrapper; };
  properties?: { [key: string]: string; };
  propertiesMetadata?: { [key: string]: PropertyMatadataWrapper; };
  propertyNames?: Array<string>;
  servicePropertyKeys?: Array<string>;
  type?: string;
  uid?: string;
  version?: string;
}

