/**
 * Ptoceti Rest Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {AttributeDefinitionWrapper} from './attributeDefinitionWrapper';


export interface ObjectClassDefinitionWrapper {
  attributeDefinitions?: Array<AttributeDefinitionWrapper>;
  description?: string;
  id?: string;
  name?: string;
}

