version: "3.7"
services:
  felix:
    image: ptoceti/felix:5.4.0-slim-stretch
    container_name: felix-slim
    ports:
      - "8080:8080"
      - "6666:6666"
    volumes:
      - ./fileinstall/:/var/felix/fileinstall
      - ./ptoceti-data:/var/ptoceti-data
  mosquitto:
    image: ptoceti/mosquitto:1.6.8-slim-stretch
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
  influxdb:
    image: influxdb:1.6.2
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-data:/var/lib/influxdb
