DROP TABLE IF EXISTS "OBJECT";
CREATE TABLE "OBJECT" ("ID" INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	"NAME" VARCHAR,
	"URI" VARCHAR,
	"URI_HASH" INTEGER,
	"CONTRACT_ID" INTEGER,
	"ISNULLABLE" BOOLEAN,
	"ICON_ID" INTEGER,
	"DISPLAYNAME" VARCHAR,
	"DISPLAY" VARCHAR,
	"WRITABLE" BOOLEAN,
	"STATUS_ID" INTEGER,
	"TYPE_ID" INTEGER,
	"PARENT_ID" INTEGER,
	"CREATED_TS" TIMESTAMP,
	"MODIFIED_TS" TIMESTAMP,
	"VALUE_TS" TIMESTAMP,
	"VALUE_INT" INTEGER,
	"VALUE_TEXT" VARCHAR,
	"VALUE_BOOL" BOOLEAN,
	"VALUE_REAL" REAL,
	"MIN" INTEGER,
	"MAX" INTEGER,
	"MIN_REAL" REAL,
	"MAX_REAL" REAL,
	"PRECISION" INTEGER,
	"RANGE_URI_ID" INTEGER,
	"UNIT" VARCHAR,
	"IN_CONTRACT_ID" INTEGER,
	"OUT_CONTRACT_ID" INTEGER,
	"OF_CONTRACT_ID" INTEGER
	);


DROP TABLE IF EXISTS "CONTRACT";
CREATE TABLE "CONTRACT" ("ID" INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, "OBJECT_ID" INTEGER);
DROP TABLE IF EXISTS "CONTRACTURI";
CREATE TABLE "CONTRACTURI" ("CONTRACT_ID" INTEGER NOT NULL, "URI_ID" INTEGER NOT NULL);

CREATE INDEX CREATE_TS_IDX ON "OBJECT"("PARENT_ID" ASC, "CREATED_TS" ASC);
CREATE INDEX PARENT_ID_IDX ON "OBJECT"("PARENT_ID" ASC);
CREATE INDEX CONTRACT_ID_IDX ON "OBJECT"("CONTRACT_ID" ASC);
CREATE INDEX MODIFIED_TS_IDX ON "OBJECT"("MODIFIED_TS" ASC);
CREATE INDEX URIHASH_IDX ON "OBJECT"("URI_HASH" ASC);

CREATE INDEX CONTRACT_OBJECT_ID_IDX ON "CONTRACT"("OBJECT_ID" ASC);

